version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_db
    environment:
      POSTGRES_DB: close_circle_local
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mysql:
    image: mysql:latest
    container_name: local-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: localdb
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql-data:/var/lib/mysql
